name: assignment3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: create log file
        run: |
          start_time=$(date -Iminutes)
          echo "$start_time" > log.txt
          echo "Dor Medina" >> log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./books
          file: ./books/Dockerfile
          push: false
          tags: books-service:latest
          outputs: type=docker,dest=/tmp/books-service.tar
      
      - name: Add log
        run: |
          if [ -f /tmp/books-service.tar ]; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
            exit 1
          fi

      - name: Upload Docker image as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: books-service
          path: /tmp/books-service.tar


      - name: Upload build log
        if: always()    
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
          
  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 29478:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing MongoDB container
        run: |
          docker ps -q --filter "ancestor=mongo" | grep -q . && docker stop $(docker ps -q --filter "ancestor=mongo") || echo "No existing MongoDB container to stop"

      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Load Docker image
        run: docker load --input books-service/books-service.tar

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pymongo
      
      - name: Print log file contents
        run: cat log/log.txt

      - name: Append to build log
        run: cat log/log.txt > log.txt

      - name: Start services 
        run: |
          docker-compose up -d && echo "Container up and running" >> log.txt || (echo "Container failed to run" >> log.txt && exit 1)

      - name: List running containers
        run: docker ps

      - name: Run tests
        env:
          MONGO_URL: mongodb://mongo:27017/library
        run: pytest -v tests/assn3_tests.py | tee assn3_test_results.txt
        continue-on-error: true

      - name: Log test results
        run: |
          if grep -q "FAILED" assn3_test_results.txt; then
            echo "Tests failed" >> log.txt
          else
            echo "Tests succeeded" >> log.txt
          fi

      - name: Upload test results
        if: always()    
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: assn3_test_results.txt

      - name: Upload updated build log
        if: always()    
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.txt
          overwrite: true

  query:
    needs: test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 29478:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing MongoDB container
        run: |
          docker ps -q --filter "ancestor=mongo" | grep -q . && docker stop $(docker ps -q --filter "ancestor=mongo") || echo "No existing MongoDB container to stop"

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: books-service
          path: /tmp

      - name: Load Docker image
        run: docker load --input /tmp/books-service.tar

      - name: Start services
        run: docker-compose up -d

      - name: Wait for Flask service to be ready
        run: |
          echo "Waiting for Flask service to be ready..."
          while ! curl -s http://localhost:5001/books; do
            sleep 5
            echo "Waiting for Flask service..."
          done
          echo "Flask service is ready!"

      - name: Print query file contents
        run: cat query.txt

      - name: Add books queries
        run: |
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"Adventures of Huckleberry Finn","ISBN":"9780520343641","genre":"Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"The Best of Isaac Asimov","ISBN":"9780385050784","genre":"Science Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"Fear No Evil","ISBN":"9780394558783","genre":"Biography"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"The Adventures of Tom Sawyer","ISBN":"9780195810400","genre":"Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"I, Robot","ISBN":"9780553294385","genre":"Science Fiction"}'
          curl -X POST http://localhost:5001/books -H "Content-Type: application/json" -d '{"title":"Second Foundation","ISBN":"9780553293364","genre":"Science Fiction"}'

      - name: Print Environment Information
        run: env

      - name: Run queries
        run: |
          echo "" > response.txt
          echo "Starting query processing..."
          while IFS= read -r query
          do
            echo "Running query: $query"
            response=$(curl -s -w "\nhttp_code:%{http_code}" -X GET "http://localhost:5001/books$query")
            echo "Raw response: $response"
            http_code=$(echo "$response" | grep "http_code:" | cut -d':' -f2)
            json_response=$(echo "$response" | sed "/http_code:/d")
          
            if [ "$http_code" -eq 200 ]; then
              echo "query: $query" >> response.txt
              echo "response: $json_response" >> response.txt
            else
              echo "query: $query" >> response.txt
              echo "response: error $http_code" >> response.txt
            fi
            echo "Completed query: $query with response: $json_response"
          done < query.txt  
        
      - name: Run queries
        run: |
          echo "" > response.txt
          echo "Starting query processing..."
          while IFS= read -r query
          do
            echo "Running query: $query"
            response=$(curl -s -w "\nhttp_code:%{http_code}" -X GET "http://localhost:5001/books$query")
            echo "Raw response: $response"
            http_code=$(echo "$response" | grep "http_code:" | cut -d':' -f2)
            json_response=$(echo "$response" | sed "/http_code:/d")
          
            if [ "$http_code" -eq 200 ]; then
              echo "query: $query" >> response.txt
              echo "response: $json_response" >> response.txt
            else
              echo "query: $query" >> response.txt
              echo "response: error $http_code" >> response.txt
            fi
            echo "Completed query: $query with response: $json_response"
          done < query.txt

      - name: Upload query results
        uses: actions/upload-artifact@v4
        with:
          name: query-results
          path: response.txt
