name: assignment3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t books-service ./books

      - name: Log build status
        run: echo "image successfully built" >> log.txt

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27018:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t books-service ./books

      - name: Stop and remove any existing containers
        run: |
          docker-compose down --volumes
          docker-compose rm -f

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for MongoDB to be ready
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 27017 && echo "MongoDB is up" && break || echo "Waiting for MongoDB..." && sleep 1;
          done

      - name: Run Pytest
        run: |
          pip install pytest requests
          pytest -v tests/assn3_tests.py > assn3_test_results.txt

      - name: Log test status
        run: echo "tests succeeded" >> log.txt

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: assn3_test_results.txt

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t books-service ./books

      - name: Stop and remove any existing containers
        run: |
          docker-compose down --volumes
          docker-compose rm -f

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for MongoDB to be ready
        run: |
          for i in `seq 1 30`; do
            nc -z localhost 27017 && echo "MongoDB is up" && break || echo "Waiting for MongoDB..." && sleep 1;
          done

      - name: Run queries
        run: |
          touch response.txt
          while IFS= read -r query
          do
            echo "query: $query" >> response.txt
            curl "http://localhost:5001/books$query" >> response.txt
          done < query.txt

      - name: Upload response file
        uses: actions/upload-artifact@v2
        with:
          name: response
          path: response.txt
